### ISSUE TITLE
Auxiliary Loss 

### ISSUE THREAD

**Issue by Barcavin** [Spazierganger/OSAN#1]
https://github.com/Spazierganger/OSAN/blob/3aa3cabc73c8c54357929347631aae0e6fa44deb/training/trainer.py#L100-L113

The training objective in the code includes an auxiliary loss. Based on the paper, this auxiliary loss is set to diversify the sampled subgraphs. In the paper, I think the loss is computed from pairwise cosine similarity. However, it seems the implementation here is to apply a KL divergence between the input and a uniform distribution. I wonder if this is equivalent to what the paper writes.

Thanks,

**Comment by chendiqian** [comment]
Nice catch, we updated our loss in the code yet by then not in the paper.
Functionally it's just for penalizing similar selection masks
